context:
  name: orjson
  version: 3.11.1

package:
  name: ${{name}}
  version: ${{ version }}

source:
- url: https://files.pythonhosted.org/packages/source/o/orjson/orjson-${{ version }}.tar.gz
  sha256: 48d82770a5fd88778063604c566f9c7c71820270c9cc9338d25147cbf34afd96

build:
  number: 1

requirements:
  build:
  - cross-python_${{target_platform}}
  - cffi == 1.17.1
  - setuptools-rust
  - rust
  - maturin

  host:
  - python
  - openssl
  - cffi == 1.17.1
  run:
  - cffi == 1.17.1
  - typing_extensions

tests:
- script: pytester
  requirements:
    build:
    - pytester
    run:
    - pytester-run
  files:
    recipe:
    - test_orjson.py


about:
  license: Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
  summary: orjson is a fast, correct JSON library for Python.
  homepage: https://github.com/ijl/orjson
  repository: https://github.com/ijl/orjson
  documentation: https://github.com/ijl/orjson
