context:
  version: 2.7.1

package:
  name: nlopt
  version: ${{ version }}

source:
- url: https://github.com/stevengj/nlopt/archive/v${{ version }}.tar.gz
  sha256: db88232fa5cef0ff6e39943fc63ab6074208831dc0031cf1545f6ecd31ae2a1a
- path: src/setup.py

build:
  number: 1

requirements:
  build:
  - cross-python_emscripten-wasm32
  - python
  - swig
  - pip
  - numpy
  host:
  - numpy
  - python
  run:
  - numpy

tests:
- script: pytester
  files:
    recipe:
    - test_import_nlopt.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  homepage: http://ab-initio.mit.edu/nlopt
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: nonlinear optimization library
