context:
  version: 7.0.2

package:
  name: traits
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/t/traits/traits-${{ version }}.tar.gz
  sha256: a563515809cb3911975de5a54209855f0b6fdb7ca6912a5e81de26529f70428c

build:
  number: 1

requirements:
  build:
  - cross-python_emscripten-wasm32
  - python
  - ${{ compiler("c") }}
  - pip
  host:
  - python
    # - setuptools
  run:
  - python

tests:
- script: pytester
  files:
    recipe:
    - test_import_traits.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  homepage: https://docs.enthought.com/traits
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: traits - explicitly typed attributes for Python
