context:
  name: pycrdt
  version: 0.12.26

package:
  name: ${{name}}
  version: ${{ version }}

source:
- url: https://github.com/jupyter-server/pycrdt/archive/refs/tags/${{version}}.tar.gz
  sha256: ba4ff0697cbbdf4280c179ba9e37ec587c921e520395222f54bbf0b0b1b76a35

build:
  number: 1

requirements:
  build:
  - cross-python_${{target_platform}}
  - cffi
  - setuptools-rust
  - rust
  - maturin

  host:
  - python
  - openssl
  - cffi
  run:
  - cffi
  - anyio
  - typing_extensions

tests:
- script: pytester
  requirements:
    build:
    - pytester
    run:
    - pytester-run
  files:
    recipe:
    - test_pycrdt.py

about:
  homepage: https://github.com/y-crdt/pycrdt
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CRDTs based on Yrs
  repository: https://github.com/y-crdt/pycrdt
  documentation: https://jupyter-server.github.io/pycrdt