context:
  name: zarr
  version: 3.0.8

package:
  name: ${{ name }}
  version: ${{ version }}

source:
- url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 88505d095af899a88ae8ac4db02f4650ef0801d2ff6f65b6d1f0a45dcf760a6d

build:
  number: 1
  script: ${{ PYTHON }} -m pip install . ${{ PIP_ARGS }}

requirements:
  build:
  - ${{ compiler('cxx') }}
  - cross-python_${{ target_platform }}
  - python
  - pip
  - hatchling
  - hatch-vcs
  host:
  - python
  run:
  - numpy
  - asciitree
  - numcodecs
  - typing-extensions
  - donfig
  - crc32c
  - packaging

tests:
- script: pytester
  files:
    recipe:
    - test_import_zarr.py
  requirements:
    build:
    - pytester
    run:
    - pytester-run

about:
  license: MIT
  license_file: LICENSE.txt
  summary: An implementation of chunked, compressed, N-dimensional arrays for Python
  homepage: https://github.com/zarr-developers/zarr-python
  documentation: https://zarr.readthedocs.io/
